Sharded lock.
Fixed at 64 locks right now. That seems about the sweet spot.

Also take minimum down a bit.

Add benchmark to README.

Standardify tests, add object comparison test. I'm not sure any of
these object comparison tests are useful.

Allow macOS to work by supplying unique map_addresses. This is a
pretty awful hack to keep macOS from bombing with shared files.  See
http://stackoverflow.com/a/35383885/4258430 for more details on why
this is necessary. Skip base mapping test on Linux since that's a
mac-only thing.

Fixing node-lmdb at 0.4.1 after Travis gave me this error:

      CXX(target) Release/obj.target/node-lmdb/src/misc.o
    ../src/misc.cpp:28:8: error: thread-local storage is not supported for the current target
    static thread_local uint32_t currentUint32Key = 0;
           ^
    1 error generated.

That was with 0.4.11. 0.4.1 was the latest version that didn't bomb.

Make sure there's actually enough room for mutexes in the shared
memory region they occupy. I think an earlier shared memory region
wasn't made large enough on a prior test run so when the new code
tried to use it there wasn't enough space allocated. This should keep
that from happening.

Remove some global locking as it's probably not necessary to totally
block access to the file when opening/closing.

Up version to 2.2.0.